name: gds
version: 0.0.1
publish_to: none
description: Grimity Design System
workspace:
  - packages/components
  - packages/foundation
  - packages/tokens

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  gds_components:
    path: packages/components
  gds_foundation:
    path: packages/foundation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  melos: ^7.4.0

melos:
  name: gds_flutter
  packages:
    - packages/**

  scripts:
    # Install: flutter pub get
    install:
      description: "Install all the dependencies"
      run: flutter pub get && dart run melos exec -c 1 -- "flutter pub get"

    # Build: Widgetbook
    build-widgetbook:
      description: "Build Widgetbook"
      run: cd packages/widgetbook && fvm exec dart run build_runner build --delete-conflicting-outputs && cd ../..

    # Format: All
    format:
      description: "Format all the files"
      run: fvm exec dart run melos exec -c 2 -- "dart fix --apply && dart format ."
